### ISSUE TITLE
use Cake\Network\Email\Email; not in 3.1.x

### ISSUE THREAD

**Issue by Isengo1989** [Lennaert/cakephp3-mandrill#6]
The use "Cake\Network\Email\Email;" is not longer Up-to-Date?

Which class to use in 3.1.9 ? Mailer/Email.php ?

**Comment by luongtrongdai** [comment]
@Lennaert Can you help me find the way to resolve this problem? I user Cakephp 3.2. Now, I see they user Cake\Mailer\Email instead of Cake\Network\Email\Email
